pull_request_rules:
  - name: Automatic merge on CI success and review
    conditions:
      - check-success=release
      - check-success=devel
      - author!=Shusei-E
      - author!=tomoya-sasaki
      - "#approved-reviews-by>=2"
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
      - base=master
      - label=auto-merge
      - label!=no-auto-merge
    actions:
      merge:
        method: merge
  - name: Automatic merge by Shusei
    conditions:
      - check-success=release
      - check-success=devel
      - author=Shusei-E
      - label=auto-merge
      - label!=no-auto-merge
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
    actions:
      merge:
        method: merge
  - name: Automatic merge by Tomoya
    conditions:
      - check-success=release
      - check-success=devel
      - author=tomoya-sasaki
      - label=auto-merge
      - label!=no-auto-merge
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
    actions:
      merge:
        method: merge
