pull_request_rules:
  - name: Automatic merge by Shusei
    conditions:
      - status-success=continuous-integration/travis-ci/pr
      - author=Shusei-E
      - base=master
      - label=auto-merge
      - label!=no-auto-merge
    actions:
      merge:
        method: merge
