# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - oldrel
  - release
  - devel
cache: packages
sudo: true
warnings_are_errors: false
os:
  - linux
#  - windows
#  - osx
dist: trusty
latex: false

# r_build_args: '--no-build-vignettes'
# r_check_args: '--ignore-vignettes'

# Manually install some packages and C++14
before_install:
  - if [ $TRAVIS_OS_NAME = 'linux' ]; then ./.travis/linux_install.sh fi
