# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - oldrel
  - release
  - devel
cache: packages
sudo: true
warnings_are_errors: true
os: linux
  env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
  addons:
    apt:
      packages:
        - g++-5
      sources: &sources
        - llvm-toolchain-precise-3.8
        - ubuntu-toolchain-r-test
dist: trusty
latex: false

before_install:
  - sudo add-apt-repository -y ppa:cran/poppler
  - sudo sudo apt-get install -y libpoppler-cpp-dev
  - Rscript -e 'install.packages(c("devtools", "ndjson"))'
