# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - oldrel
  - release
  - devel
cache: packages
sudo: true
warnings_are_errors: true
os: linux
dist: trusty
latex: false

before_install:
  - sudo add-apt-repository -y ppa:cran/poppler
  - sudo sudo apt-get install -y libpoppler-cpp-dev
  - Rscript -e 'install.packages(c("devtools", "ndjson"))'
