# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - oldrel
  - release
#  - devel
cache: packages
sudo: true
warnings_are_errors: false
os:
  - linux
  - osx
dist: trusty
latex: false

# Manually install some packages and C++14
before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo add-apt-repository -y ppa:cran/poppler  ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo sudo apt-get install -y libpoppler-cpp-dev  ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then mkdir -p ~/.R  ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then echo "CXX14FLAGS=-O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function  -Wno-macro-redefined" >> ~/.R/Makevars  ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then echo "CXX14=g++ -std=c++1y -fext-numeric-literals -fPIC" >> ~/.R/Makevars  ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then Rscript -e 'install.packages(c("devtools", "ndjson"))'  ; fi
