# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - oldrel
  - release
  - devel
cache: packages
sudo: true
warnings_are_errors: false
os:
  - linux
  - windows
  - osx
dist: trusty
latex: false

# r_build_args: '--no-build-vignettes'
# r_check_args: '--ignore-vignettes'

# Manually install some packages and C++14
before_install:
  - sudo add-apt-repository -y ppa:cran/poppler
  - sudo sudo apt-get install -y libpoppler-cpp-dev
  - mkdir -p ~/.R
  - echo "CXX14FLAGS=-O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function  -Wno-macro-redefined" >> ~/.R/Makevars
  - echo "CXX14=g++ -std=c++1y -fext-numeric-literals -fPIC" >> ~/.R/Makevars
  - Rscript -e 'install.packages(c("devtools", "ndjson"))'
